merges:
  - action: delete_branch

default:
  close:
    comment: '⚠️ This has been marked $LABEL to be closed in $DELAY'
    delay: '30 days'

labels:
  duplicate: close
  wontfix: close
  invalid: close
  'merge when passing': merge
  'rebase when passing': rebase
  'new contributor':
    delay: 5s
	message: "Thanks for making your first contribution! :slightly_smiling_face:"
  question:
    message: "This has been marked question, further information is requested"

comments: 
  - action: label 
    pattern: /duplicate of/i 
    labels: 
      - duplicate 
